apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-service-deployment
  labels:
    app: credit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: credit-service
  template:
    metadata:
      labels:
        app: credit-service
    spec:
      containers:
      - name: credit-service
        image: credit-service:1.14.2
